### ISSUE TITLE
About the dataloader

### ISSUE THREAD

**Issue by BoYangXDU** [Hengwei-Zhao96/T-HOneCls#2]
Hengwei,

Thank you for your valuable contributions to PU learning for hyperspectral image analysis, particularly with absNegative, HOneCls, and T-HOneCls.

I'm trying to follow your work, but I've noticed some differences in the data loading files for the three datasets. Specifically, for dataset_HongHu, there are the following lines:
https://github.com/Hengwei-Zhao96/T-HOneCls/blob/7cf2de6668a4a7ca5b1812f3ea42865355940152/HOC/datasets/dataset_HongHu.py#L32-L35

However, I couldn't find similar code for dataset_HanChuan and dataset_LongKou. Could you please explain the differences between these configurations?

Thank you very much.

Best regards,
Bo

**Comment by Hengwei-Zhao96** [comment]
Howdy,

Apologies for the delayed response!

The difference arises from how the labels in these hyperspectral datasets are structured. In the HongHu dataset, both the training and testing labels come from the same file, whereas in the other two datasets, they are separated. As a result, we need to configure the process differently.

Best,

Hengwei Zhao

**Comment by BoYangXDU** [comment]
With great thanks for your help. It is really helpful. I will close this issue.
Best.

Yang
